apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns
data:
  Corefile: |
    example.com {
        hosts /opt/data/hostsfile
        log
        roundrobin random
    }
  hostsfile: |
    1.1.1.1 cloud.example.com
    3.3.3.3 cloud.example.com
    2.2.2.2 cloud.example.com
    2001:502:f3ff::e8 cloud.example.com
    2610:a1:1014::e8 cloud.example.com
---
apiVersion: v1
kind: Service
metadata:
  name: coredns
spec:
  type: ClusterIP
  ports:
  - port: 5053
    targetPort: 5053
    protocol: TCP
    name: coredns-tcp
  - port: 5053
    targetPort: 5053
    protocol: UDP
    name: coredns-udp
  selector:
    app: coredns
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: coredns
spec:
  template:
    metadata:
      labels:
        app: coredns
    spec:
      containers:
      - name: coredns
        image: kuritka/coredns:v0.0.4
        args: ["-p","5053","-conf", "/opt/data/Corefile"]
        volumeMounts:
        - name: config-files
          mountPath: /opt/data
      volumes:
      - name: config-files
        configMap:
          name: coredns

  replicas: 1
  selector:
    matchLabels:
      app: coredns
---
apiVersion: v1
kind: Pod
metadata:
  name: dns1
spec:
  containers:
  - name: dnsutils
    image: k8s.gcr.io/e2e-test-images/jessie-dnsutils:1.3
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
  restartPolicy: Always
---
apiVersion: v1
kind: Pod
metadata:
  name: dns2
spec:
  containers:
  - name: dnsutils
    image: k8s.gcr.io/e2e-test-images/jessie-dnsutils:1.3
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
  restartPolicy: Always
